routes/admin.php
| Admin Routes
|--------------------------------------------------------------------------
|
| Here is where you can register admin routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/admin', 'HomeController@admin_dashboard')->name('admin.dashboard')->middleware(['auth', 'admin']);
Route::group(['prefix' =>'admin', 'middleware' => ['auth', 'admin']], function(){
    
//Marg Routes
Route::get('marg/sync', 'MargController@sync')->name('marg-sync');
Route::get('marg/product/unlisted', 'MargController@unlistedProduct')->name('unlistedProduct');
Route::post('marg/product/unlisted', 'MargController@unlistedProductMap')->name('unlistedProduct.Map');
Route::get('marg/product/unmapped', 'MargController@unmappedProduct');
Route::get('marg/customer/unlisted', 'MargController@unlistedCustomer')->name('unlistedCustomer');
Route::post('marg/customer/unlisted', 'MargController@unlistedCustomerMap')->name('unlistedCustomer.Map');
Route::get('marg/customer/unmapped', 'MargController@unmappedCustomer')->name('unmappedCustomer');
Route::post('marg/customer/unmapped', 'MargController@unmappedCustomerMap')->name('unmappedCustomer.Map');
Route::get('marg/order/pending', 'MargController@order_pending')->name('marg.order.pending');
Route::get('marg/order/processed', 'MargController@order_processed')->name('marg.order.processed');
Route::post('marg/customer', 'MargController@get_marg_customer')->name('marg.customer');
Route::post('marg/product', 'MargController@get_marg_product')->name('marg.product');
Route::post('marg/customer/map', 'MargController@marg_customer_map')->name('marg.customer.map');
Route::post('marg/order/send', 'MargController@marg_order_send')->name('marg.order.send');
Route::post('marg/order/product', 'MargController@marg_order_product')->name('marg.order.product');
Route::get('marg/debug', 'MargController@debug')->name('marg.debug');

    
//Expenses
	Route::get('/expenses', array('as' => 'Expenses', 'uses' => 'ExpensesController@Expenses'));
	Route::get('/expenses/create', array('as' => 'CreateExpense', 'uses' => 'ExpensesController@CreateExpense'));
	Route::post('/expenses/save', array('as' => 'SaveExpense', 'uses' => 'ExpensesController@SaveExpense'));
	Route::get('/expenses/edit/{id}', array('as' => 'ExpensesEdit', 'uses' => 'ExpensesController@ExpensesEditView'));
	Route::post('/expenses/update/{id}', array('as' => 'ExpensesEditPost', 'uses' => 'ExpensesController@ExpensesEditPost'));
	Route::get('/expenses/view/{id}', array('as' => 'ExpensesView', 'uses' => 'ExpensesController@ExpensesView'));
	Route::post('/expenses/delete', array('as' => 'ExpenseDelete', 'uses' => 'ExpensesController@ExpenseDelete'));
	Route::get('/expenses/addpayment', array('as' => 'ExpensePaymentAdd', 'uses' => 'ExpensesController@ExpensePaymentAdd'));
	Route::get('/expenses/addpayment/{id}', array('as' => 'ExpensePaymentAddWithID', 'uses' => 'ExpensesController@ExpensePaymentAddWithID'));
	Route::post('/expenses/savepayment', array('as' => 'ExpensePaymentSave', 'uses' => 'ExpensesController@ExpensePaymentSave'));
	Route::post('/expenses/deletepayment', array('as' => 'ExpensePaymentDelete', 'uses' => 'ExpensesController@ExpensePaymentDelete'));
	Route::get('/expenses/createcategory', array('as' => 'CreateCategory', 'uses' => 'ExpensesController@CreateCategory'));
	Route::post('/expenses/categorysave', array('as' => 'SaveCategory', 'uses' => 'ExpensesController@SaveCategory'));
	Route::get('/expenses/category', array('as' => 'ExpenseCategory', 'uses' => 'ExpensesController@Category'));
	Route::get('/expenses/categoryedit/{id}', array('as' => 'CategoryEditView', 'uses' => 'ExpensesController@CategoryEditView'));
	Route::post('/expenses/categoryupdate/{id}', array('as' => 'CategoryEditPost', 'uses' => 'ExpensesController@CategoryEditPost'));
	Route::post('/expenses/categorydelete', array('as' => 'ExpenseCategoryDelete', 'uses' => 'ExpensesController@CategoryDelete'));

//product purchase
	Route::get('/product/purchase', 'ProductPurchaseController@Product')->name('product.purchase.index');
	Route::get('/product/purchase/create', 'ProductPurchaseController@ProductCreate')->name('product.purchase.create');
	Route::post('/product/purchase/save', 'ProductPurchaseController@ProductAdd')->name('product.purchase.save');
	Route::get('/product/purchase/view/{id}', 'ProductPurchaseController@ProductPurchaseView')->name('product.purchase.view');
	Route::get('/product/purchase/delete', 'ProductPurchaseController@ProductDelete')->name('product.purchase.delete');
	
	Route::get('wallet-history/{id}', 'WalletController@walletHistory')->name('wallet-history');
    
    
	Route::resource('categories','CategoryController');
	Route::get('/categories/destroy/{id}', 'CategoryController@destroy')->name('categories.destroy');
	Route::post('/categories/featured', 'CategoryController@updateFeatured')->name('categories.featured');

	Route::resource('subcategories','SubCategoryController');
	Route::get('/subcategories/destroy/{id}', 'SubCategoryController@destroy')->name('subcategories.destroy');
	//die('kkggg');
	Route::post('/ajax/getsubcategory', 'SubCategoryController@getsubcats')->name('ajax.getsubcategory');
	Route::post('/ajax/getsubsubcategory', 'SubSubCategoryController@getSubsubcatsBy')->name('ajax.getsubsubcategory');
	Route::resource('subsubcategories','SubSubCategoryController');
	Route::get('/subsubcategories/destroy/{id}', 'SubSubCategoryController@destroy')->name('subsubcategories.destroy');


	Route::resource('brands','BrandController');
	Route::get('/brands/destroy/{id}', 'BrandController@destroy')->name('brands.destroy');

	
	Route::post('/ajax/getAllProduct', 'ProductController@getAllProductBySubCatId')->name('ajax.getAllProduct');

	Route::get('/products/admin','ProductController@admin_products')->name('products.admin');
	Route::get('/products/seller','ProductController@seller_products')->name('products.seller');
	Route::get('/products/sellerVerified/{id?}','ProductController@seller_products_verified')->name('products.sellerVerified');
	Route::get('/products/create','ProductController@create')->name('products.create');
	Route::get('/products/admin/{id}/edit','ProductController@admin_product_edit')->name('products.admin.edit');
	Route::get('/products/seller/{id}/edit','ProductController@seller_product_edit')->name('products.seller.edit');
	Route::post('/products/todays_deal', 'ProductController@updateTodaysDeal')->name('products.todays_deal');
	Route::post('/products/get_products_by_subsubcategory', 'ProductController@get_products_by_subsubcategory')->name('products.get_products_by_subsubcategory');
	Route::post('/products/get_products_by_category', 'ProductController@get_products_by_category')->name('products.get_products_by_category');
	Route::post('/products/vendor/assign', 'ProductController@vendor_assign')->name('products.vendor_assign');
	Route::get('/products/vendor/remove/{id}', 'ProductController@vendor_remove')->name('products.vendor_remove');
	
	Route::get('/bulk-product-remove', 'ProductController@bulk_remove_view')->name('bulk_remove_view');
	Route::post('/bulk-product-remove', 'ProductController@bulk_remove')->name('bulk_remove');

	Route::resource('sellers','SellerController');
	Route::get('/sellers/destroy/{id}', 'SellerController@destroy')->name('sellers.destroy');
	Route::get('/sellers/view/{id}/verification', 'SellerController@show_verification_request')->name('sellers.show_verification_request');
	Route::get('/sellers/approve/{id}', 'SellerController@approve_seller')->name('sellers.approve');
	Route::get('/sellers/reject/{id}', 'SellerController@reject_seller')->name('sellers.reject');
	Route::post('/sellers/payment_modal', 'SellerController@payment_modal')->name('sellers.payment_modal');
	Route::get('/seller/payments', 'PaymentController@payment_histories')->name('sellers.payment_histories');
	Route::get('/seller/payments/show/{id}', 'PaymentController@show')->name('sellers.payment_history');
    Route::post('/sellers/profile_modal', 'SellerController@profile_modal')->name('sellers.profile_modal');
    Route::post('/sellers/approved', 'SellerController@updateApproved')->name('sellers.approved');
    Route::get('/seller/sellercommission', 'SellerController@seller_commission')->name('sellers.sellercommission');
    Route::get('/seller/commissionview', 'SellerController@commission_view')->name('sellers.commissionview');
    Route::post('addSellerCommission', 'SellerController@addSellerCommission')->name('addSellerCommission');
    Route::post('editSellerCommission', 'SellerController@editSellerCommission')->name('editSellerCommission');
    
   // Route::post('SellerCommission/view/{id}', 'SellerController@SellerCommissionShow')->name('SellerCommission');
   Route::get('/sellercomission/{id}/show', 'SellerController@showComission')->name('sellercomission.show');
   //Route::get('/orders/{id}/show', 'OrderController@show')->name('orders.show');
    
    
    
    //Delete seller config
    Route::post('/deleteSellerCommisionConfig', 'SellerController@deleteSellerCommisionConfig')->name('deleteSellerCommisionConfig');
    
	Route::resource('vendors','VendorController');
    Route::post('/vendors/profile_modal', 'VendorController@profile_modal')->name('vendors.profile_modal');
    Route::post('/vendors/active', 'VendorController@active_vendor')->name('vendors.activated');
    Route::get('/products/vendor/{id}', 'ProductController@vendor_products')->name('products.vendor');
    Route::get('/vendors/view/expenses', 'VendorController@vendor_expenses')->name('vendor.expenses');
    Route::post('/vendors/create/login', 'VendorController@create_login')->name('vendor.create_login');


	Route::get('/customers/export', 'CustomerController@ExportExcel')->name('customers.export');
	//Order export
	Route::get(
	'/order/export', 'OrderController@ExportExcel')->name('order.export');

routes/web.php
                             
                             echo "MySQL Select Selected coloumn Data Using First (Laravel): $execution_time <br />"; 
                                                    $start_time = microtime(true);
                                                    $id = 424;
                                                        $product = Cache::rememberForever('Product:'.$id, function () use ($id) {
                                                                return \App\Product::find($id);
                                                        });
                                                        $end_time = microtime(true); 
                              
                            // Calculate script execution time 
                            $execution_time = ($end_time - $start_time); 
                             
                              echo "Getting Redis cached Data : $execution_time <br />"; 
                                                    $start_time = microtime(true);
                                                    $id = 424;
                                                        $product = Cache::rememberForever('Product:Published:'.$id, function () use ($id) {
                                                                return \App\Product::select('id', 'published')->where('id',$id)->first();
                                                        });
                                                        $end_time = microtime(true); 
                              
                            // Calculate script execution time 
                            $execution_time = ($end_time - $start_time); 
                             
                              echo "Getting Redis cached Data : $execution_time <br />"; 
d(Request::all());
d(Session::all());
d(Auth::User()); 
}); 

Route::get("sitemap.xml", 'SitemapController@sitemap');
Route::get("sitemaps/{fileName}", 'SitemapController@sitemaps');
//Feedback Form layout

Route::get("feedback-form", 'CustomerController@feedbackForm')->name('feedback-form');
Route::get("review-list/{slug}", 'ProductController@reviewList')->name('review-list');
Route::post("savefeedback/form", 'CustomerController@savefeedback')->name('savefeedback.form');
//Add pharmacy order
Route::get("pharmacy-enquiry", 'CustomerController@pharmacykForm')->name('pharmacy-enquiry');
Route::post("add-pharmacy-form", 'CustomerController@pharmacykFormAdd')->name('add-pharmacy-form');



Route::get('/testmail', function() {
    $dataEmail = array('email' => 'imarjun12@gmail.com', 'name' => 'Arjun');
    
    if(isset($dataEmail['lname'])){
       $dataEmail['lname'] = $dataEmail['name']." ".$dataEmail['lname']; 
    }
    $order = \App\Order::find(28);
echo  $render = view('emails.order_confirmation_client', ['array' => array('order' => $order)])->render();
die();
    Mail::send('emails.order_confirmation_client', ['array' => array('order' => $order)], function ($m) use ($dataEmail) {
            $m->to($dataEmail['email'], $dataEmail['name'])->subject('Alde Bazaar :: Order Confirmation');
        });
});

Route::get('/cron', function() {
     $exitCode = Artisan::call('calculateReferralCommision');
     return 'Done';
 });

Route::get('/cron2', function() {
     $exitCode = Artisan::call('calculateCategoryCashBack');
     return 'Done';
 });
 
//Clear route cache:
 Route::get('/route-cache', function() {
     $exitCode = Artisan::call('route:cache');
     return 'Routes cache cleared';
 });

 //Clear config cache:
 Route::get('/config-cache', function() {
     $exitCode = Artisan::call('config:cache');
     return 'Config cache cleared';
 }); 
 //Clear config cache:
 Route::get('/config-clear', function() {
     $exitCode = Artisan::call('config:clear');
     return 'Config cache cleared';
 }); 


// Clear application cache:
 Route::get('/clear-cache', function() {
     $exitCode = Artisan::call('cache:clear');
     return 'Application cache cleared';
 });

 // Clear view cache:
 Route::get('/view-clear', function() {
     $exitCode = Artisan::call('view:clear');
     return 'View cache cleared';
 });
Route::get('/testemail', function() {
    return view('emails.order_confirmation_client');
});
//demo
Route::get('/testm', function() {
   return view('frontend.test'); 
});
Route::get('/testm1', function() {
   return view('frontend.test_bak'); 
});
Route::get('/demo/cron_1', 'DemoController@cron_1');
Route::get('/demo/cron_2', 'DemoController@cron_2');


Route::get('/resize', 'HomeController@imgResize')->name('img.resize');

Route::get('/rebuildredis', 'HomeController@rebuildRedis');

Auth::routes(['verify' => true]);
Route::get('/logout', '\App\Http\Controllers\Auth\LoginController@logout');
Route::post('/language', 'LanguageController@changeLanguage')->name('language.change');
Route::post('/currency', 'CurrencyController@changeCurrency')->name('currency.change');

Route::get('/social-login/redirect/{provider}', 'Auth\LoginController@redirectToProvider')->name('social.login');
Route::get('/social-login/{provider}/callback', 'Auth\LoginController@handleProviderCallback')->name('social.callback');
Route::post('/social-login/apple/callback', 'Auth\LoginController@handleProviderCallback')->name('social.callback.apple');
Route::get('/users/redirect', 'HomeController@userRedirect')->name('users.redirect');
Route::get('/users/login', 'HomeController@login')->name('user.login');
Route::get('/users/registration', 'HomeController@registration')->name('user.registration');
//Route::post('/users/login', 'HomeController@user_login')->name('user.login.submit');
Route::post('/users/login/cart', 'HomeController@cart_login')->name('cart.login.submit');
Route::post('/users/login/generate/otp', 'HomeController@login_otp_generate')->name('generate.otp.login');
Route::post('/users/login', 'HomeController@user_login')->name('user.login.validate');

//Check pincode
Route::post('/ajax/checkpicode', array('as' => 'checkpicode', 'uses' => 'HomeController@checkpicode'));
Route::post('/ajax/getpincode', array('as' => 'getpincode', 'uses' => 'HomeController@getpincode'));
Route::post('/ajax/pharmacyStatus',  'CustomerController@updatePharmacy');



Route::post('/subcategories/get_subcategories_by_category', 'SubCategoryController@get_subcategories_by_category')->name('subcategories.get_subcategories_by_category');
Route::post('/subsubcategories/get_subsubcategories_by_subcategory', 'SubSubCategoryController@get_subsubcategories_by_subcategory')->name('subsubcategories.get_subsubcategories_by_subcategory');
Route::post('/subsubcategories/get_brands_by_subsubcategory', 'SubSubCategoryController@get_brands_by_subsubcategory')->name('subsubcategories.get_brands_by_subsubcategory');
Route::post('/subsubcategories/get_attributes_by_subsubcategory', 'SubSubCategoryController@get_attributes_by_subsubcategory')->name('subsubcategories.get_attributes_by_subsubcategory');

//Home Page
Route::get('/', 'HomeController@index')->name('home');
Route::post('/home/section/featured', 'HomeController@load_featured_section')->name('home.section.featured');
Route::post('/home/section/best_selling', 'HomeController@load_best_selling_section')->name('home.section.best_selling');
Route::post('/home/section/brand_banner', 'HomeController@load_brand_banner_section')->name('home.section.brand_banner');
Route::post('/home/section/home_categories', 'HomeController@load_home_categories_section')->name('home.section.home_categories');
Route::post('/home/section/home_categories2', 'HomeController@load_home_categories_section2')->name('home.section.home_categories2');
Route::post('/home/section/home_categories3', 'HomeController@load_home_categories_section3')->name('home.section.home_categories3');
Route::post('/home/section/best_sellers', 'HomeController@load_best_sellers_section')->name('home.section.best_sellers');
//category dropdown menu ajax call
Route::post('/categoryp/nav-element-list', 'HomeController@get_category_items')->name('category.elements');

//Flash Deal Details Page
Route::get('/flash-deal/{slug}', 'HomeController@flash_deal_details')->name('flash-deal-details');

Route::get('/feature-product-list', 'HomeController@featureproductList')->name('feature-product-list');

Route::get('/best-selling', 'HomeController@bestSelling')->name('best-selling');


Route::get('/customer-products', 'CustomerProductController@customer_products_listing')->name('customer.products');
Route::get('/customer-products?subsubcategory={subsubcategory_slug}', 'CustomerProductController@search')->name('customer_products.subsubcategory');
Route::get('/customer-products?subcategory={subcategory_slug}', 'CustomerProductController@search')->name('customer_products.subcategory');
Route::get('/customer-products?category={category_slug}', 'CustomerProductController@search')->name('customer_products.category');
Route::get('/customer-products?city={city_id}', 'CustomerProductController@search')->name('customer_products.city');
Route::get('/customer-products?q={search}', 'CustomerProductController@search')->name('customer_products.search');
Route::get('/customer-product/{slug}', 'CustomerProductController@customer_product')->name('customer.product');
Route::get('/customer-packages', 'HomeController@premium_package_index')->name('customer_packages_list_show');



Route::get('/product/{slug}', 'HomeController@product')->name('product');
Route::get('/products', 'HomeController@listing')->name('products');
Route::post('/products/url', 'ProductController@productURL')->name('products.url');
Route::get('/category/{category_slug}', 'HomeController@category_view')->name('products.category');
Route::get('/custom/{category_slug}/{custom_name_slug}', 'HomeController@product_custom')->name('products.custom');
Route::get('/subcategory/{subcategory_slug}', 'HomeController@category_view')->name('products.subcategory1');

resources/views/frontend/seller/category/edit.blade.php
@extends('layouts.app')

@section('content')
@if($errors->any())
			<div class="alert alert-danger">
				<strong>Whoops! </strong> There were some problems with your input.<br/><br/>
				<ul>
					@foreach($errors->all() as $error)
						<li>{{ $error }}</li>
					@endforeach
				</ul>
			</div>
		@endif
<div class="col-12 ">
    <div class="panel">
        <div class="panel-heading">
            <h3 class="panel-title">{{__('Category Information')}}</h3>
        </div>

        <!--Horizontal Form-->
        <!--===================================================-->
        <form class="form-horizontal" action="{{ route('categories.update', $category->id) }}" method="POST" enctype="multipart/form-data">
            <input name="_method" type="hidden" value="PATCH">
        	@csrf
        	<span class="err text-danger"></span>
            <div class="panel-body">
                <div class="form-group">
                    <label class="col-sm-2 control-label" for="name">{{__('Name')}}</label>
                    <div class="col-sm-10">
                        <input type="text" placeholder="{{__('Name')}}" id="name" name="name" class="form-control" required value="{{$category->name}}">
                    </div>
                     <input type="hidden" name="digital" value="0" />
                </div>
				<div class="form-group">
                    <label class="col-sm-2 control-label" for="banner">{{__('Menu Banner')}}</label>
                    <div class="col-sm-4">
                        <input type="file" id="menu_banner" name="menu_banner" class="form-control" accept="image/png,image/jpg,image/jpeg">
						<small class="text-danger"> (490px * 550px)</small>
                    </div>
                
                    <label class="col-sm-2 control-label" for="banner">{{__('Desktop Icon')}}</label>
                    <div class="col-sm-4">
                        <input type="file" id="banner" name="banner" class="form-control" accept="image/png,image/jpg,image/jpeg">
						<small class="text-danger">(197px * 186px)</small>
                    </div>
                </div>
                <div class="form-group">
                    <label class="col-sm-2 control-label" for="icon">{{__('Mobile Icon')}} </label>
                    <div class="col-sm-10">
                        <input type="file" id="icon" name="icon" class="form-control" accept="image/png,image/jpg,image/jpeg">
						<small class="text-danger">(197px * 186px)</small>
                    </div>
                </div>
                <div class="form-group">
                    <label class="col-sm-2 control-label" for="bg_img">{{__('Background Image')}} </label>
                    <div class="col-sm-10">
                        <input type="file" id="bg_img" name="bg_img" class="form-control" accept="image/png,image/jpg,image/jpeg">
						<small class="text-danger">(222px * 250px)</small>
                    </div>
                </div>
                <div class="form-group">
                    <label class="col-sm-2 control-label" for="bg_color">{{__('Background Color')}}</label>
                    <div class="col-sm-4">
                        <input type="text" id="bg_color" name="bg_color" value="{{$category->background_color}}" class="form-control" placeholder="{{__('Background Color')}}">
					
                    </div>
                
                    <label class="col-sm-2 control-label" for="text_color">{{__('Text Color')}}</label>
                    <div class="col-sm-4">
                        <input type="text" id="banner" name="text_color" value="{{$category->text_color}}" class="form-control" placeholder="{{__('Text Color')}}">
                    </div>
                </div>
                
				<div class="form-group">
                    <label class="col-sm-2 control-label">{{__('Top Sku')}}<em> (Seperated by Comma)</em></label>
                    <div class="col-sm-10">
                        <textarea class="form-control" name="top_sku">@if($category->top_sku != null){{ trim(implode(",", json_decode($category->top_sku,true))) }} @endif</textarea>
                    </div>
                </div>
               <div class="form-group">
                    <label class="col-sm-2 control-label">{{__('Meta Title')}}</label>
                    <div class="col-sm-10">
                        <input type="text" class="form-control" name="meta_title" value="{{ $category->meta_title }}" placeholder="{{__('Meta Title')}}">
                    </div>
                </div>
                <div class="form-group">
                    <label class="col-sm-2 control-label">{{__('Meta Description')}}</label>
                    <div class="col-sm-10">
                        <textarea name="meta_description" rows="8" class="form-control">{{ $category->meta_description }}</textarea>
                    </div>
                </div>
                <div class="form-group">
                    <label class="col-sm-2 control-label">{{__('Meta Keywords')}}</label>
                    <div class="col-sm-10">
                        <input type="text" class="form-control" name="meta_keywords[]" value="{{ $category->meta_keywords }}" placeholder="Type to add a keyword" data-role="tagsinput">
                    </div>
                </div>
                <div class="form-group">
                    <label class="col-sm-2 control-label" for="name">{{__('Slug')}}</label>
                    <div class="col-sm-10">
                        <input type="text" placeholder="{{__('Slug')}}" id="slug" name="slug" value="{{ $category->slug }}" class="form-control">
                    </div>
                </div>
				<div class="form-group">
                    <label class="col-sm-2 control-label" for="position">{{__('Position')}}</label>
                    <div class="col-sm-4">
                    	@php
        					$dbposition=\App\Category::get();
        					$allposiotns=array();
        					foreach($dbposition as $value){
        							array_push($allposiotns,$value->position);
        					}						
        				@endphp
                        <select name="position" class="form-control demo-select2-placeholder">
    						<option value="{{$category->position}}" selected>{{$category->position}}</option>
    						@for($n=1;$n<=40;$n++)
    							@if(!in_array($n,$allposiotns))
    								<option value="{{$n}}">{{$n}}</option>
    							@endif
    						@endfor
    					</select>
                    </div>
                
                    <label class="col-sm-2 control-label" for="position">{{__('Discount (%)')}}</label>
                    <div class="col-sm-4">
                        <input type="text" min=0 value="{{ $category->discount }}" class="form-control" name="category_discount" placeholder="{{__('Category Discount')}}">
                    </div>
                </div>
				<div class="form-group">
                    <label class="col-sm-1 control-label">{{__('Content')}}</label>
                    <div class="col-sm-11">
                        <textarea class="editor" name="category_content">{{ $category->content }}</textarea>
                    </div>
                </div>
                <div class="form-group">
					<div class="col-12" style="background:#e1e1e1;padding:5px">
						<h3>Return Policy</h3>
					</div>
				</div>
				<div class="form-group">
                    <label class="col-sm-2 control-label">{{__('Return Days')}}</label>
                    <div class="col-sm-10">
                        <input type="number" class="form-control" name="return_days" value="{{ $category->return_days }}" placeholder="{{__('eg. 7')}}" min="1" max="20">
                    </div>
                </div>
				<div class="form-group">
                    <label class="col-sm-2 control-label">{{__('Heading')}}</label>
                    <div class="col-sm-10">
                        <input type="text" class="form-control" name="policy_heading" value="{{ $category->policy_heading }}" placeholder="{{__('eg. 7 Days Returns')}}">
                    </div>
                </div>
                <div class="form-group">
                    <label class="col-sm-2 control-label">{{__('Content')}}</label>
                    <div class="col-sm-10">
                        <textarea name="policy_content" rows="8" class="form-control" placeholder="eg. 7 Day FREE Returns. This item is eligible for return within 7 days of delivery.">{{ $category->policy_content }}</textarea>
                    </div>
                </div>
                @if (\App\BusinessSetting::where('type', 'category_wise_commission')->first()->value == 1)
                   <!-- <div class="form-group">
                        <label class="col-sm-2 control-label" for="name">{{__('Commission Rate')}}</label>
                        <div class="col-sm-8">
                            <input type="number" min="0" step="0.01" id="commision_rate" name="commision_rate" value="{{ $category->commision_rate }}" class="form-control">
                        </div>
                        <div class="col-lg-2">
                            <option class="form-control">%</option>
                        </div>
                    </div>-->
                @endif
                
                <div class="form-group">
                    <label class="col-sm-2 control-label">{{__('Menu Display')}}</label>
                    <div class="col-sm-10">
                        <select name="display" class="form-control">
                            <option value="1" @if($category->display == 1) selected @endif>Show</option>
                            <option value="0" @if($category->display == 0) selected @endif>Hide</option>
                        </select>
                    </div>
                </div>
            </div>
            <div class="panel-footer text-right">
                <button class="btn btn-purple" type="submit">{{__('Save')}}</button>
            </div>
			<br/>
        </form>
        <!--===================================================-->
        <!--End Horizontal Form-->

    </div>
</div>
<script type="text/javascript">
	$('INPUT[type="file"]').change(function () {
		var ext = this.value.match(/\.(.+)$/)[1];
	    switch (ext) {
			case 'jpg':
			case 'jpeg':
			case 'png':
			    $(".err").text('');
				$('#submitbtn').attr('disabled', false);
				break;
			default:
				$(".err").text('This is not an allowed file type.');
				this.value = '';
		}
	});
</script>
@endsection